/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

/**
 *
 * @author rauli
 */
public class BarraMenus extends javax.swing.JFrame {

    /**
     * Creates new form BarraMenus
     */
    public BarraMenus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        REGISTRAR = new javax.swing.JMenu();
        FrmRegistrarProducto = new javax.swing.JMenuItem();
        FrmRegistrarVenta = new javax.swing.JMenuItem();
        CONSULTAR = new javax.swing.JMenu();
        FrmConsultarProducto = new javax.swing.JMenuItem();
        FrmConsultarInventario = new javax.swing.JMenuItem();
        FrmConsultarActuInventario = new javax.swing.JMenuItem();
        FrmConsultarVenta = new javax.swing.JMenuItem();
        ELIMINAR = new javax.swing.JMenu();
        FrmEliminarProducto = new javax.swing.JMenuItem();
        FrmEliminarVenta = new javax.swing.JMenuItem();
        ACTUALIZAR = new javax.swing.JMenu();
        FrmActualizarProducto = new javax.swing.JMenuItem();
        FrmActualizarInventario = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        FrmImprimirVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 953, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        REGISTRAR.setText("REGISTRAR");
        REGISTRAR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        FrmRegistrarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmRegistrarProducto.setText("Producto");
        FrmRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmRegistrarProductoActionPerformed(evt);
            }
        });
        REGISTRAR.add(FrmRegistrarProducto);

        FrmRegistrarVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmRegistrarVenta.setText("Venta");
        FrmRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmRegistrarVentaActionPerformed(evt);
            }
        });
        REGISTRAR.add(FrmRegistrarVenta);

        jMenuBar1.add(REGISTRAR);

        CONSULTAR.setText("CONSULTAR");
        CONSULTAR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        FrmConsultarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmConsultarProducto.setText("Producto");
        FrmConsultarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmConsultarProductoActionPerformed(evt);
            }
        });
        CONSULTAR.add(FrmConsultarProducto);

        FrmConsultarInventario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmConsultarInventario.setText("Inventario");
        FrmConsultarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmConsultarInventarioActionPerformed(evt);
            }
        });
        CONSULTAR.add(FrmConsultarInventario);

        FrmConsultarActuInventario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmConsultarActuInventario.setText("Actualizaciones Inventario");
        FrmConsultarActuInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmConsultarActuInventarioActionPerformed(evt);
            }
        });
        CONSULTAR.add(FrmConsultarActuInventario);

        FrmConsultarVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmConsultarVenta.setText("Venta");
        FrmConsultarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmConsultarVentaActionPerformed(evt);
            }
        });
        CONSULTAR.add(FrmConsultarVenta);

        jMenuBar1.add(CONSULTAR);

        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        FrmEliminarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmEliminarProducto.setText("Producto");
        FrmEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmEliminarProductoActionPerformed(evt);
            }
        });
        ELIMINAR.add(FrmEliminarProducto);

        FrmEliminarVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmEliminarVenta.setText("Venta");
        FrmEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmEliminarVentaActionPerformed(evt);
            }
        });
        ELIMINAR.add(FrmEliminarVenta);

        jMenuBar1.add(ELIMINAR);

        ACTUALIZAR.setText("ACTUALIZAR");
        ACTUALIZAR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        FrmActualizarProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmActualizarProducto.setText("Producto");
        FrmActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmActualizarProductoActionPerformed(evt);
            }
        });
        ACTUALIZAR.add(FrmActualizarProducto);

        FrmActualizarInventario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmActualizarInventario.setText("Inventario");
        FrmActualizarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmActualizarInventarioActionPerformed(evt);
            }
        });
        ACTUALIZAR.add(FrmActualizarInventario);

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem6.setText("Venta");
        ACTUALIZAR.add(jMenuItem6);

        jMenuBar1.add(ACTUALIZAR);

        jMenu1.setText("IMPRIMIR");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        FrmImprimirVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FrmImprimirVenta.setText("Venta");
        FrmImprimirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmImprimirVentaActionPerformed(evt);
            }
        });
        jMenu1.add(FrmImprimirVenta);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FrmRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmRegistrarProductoActionPerformed
         FrmRegistrarProducto ventana = new FrmRegistrarProducto();
         Escritorio.add(ventana);
         ventana.show();
    }//GEN-LAST:event_FrmRegistrarProductoActionPerformed

    private void FrmConsultarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmConsultarProductoActionPerformed
        FrmConsultarProducto ventana = new FrmConsultarProducto();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmConsultarProductoActionPerformed

    private void FrmEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmEliminarProductoActionPerformed
        FrmEliminarProducto ventana = new FrmEliminarProducto();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmEliminarProductoActionPerformed

    private void FrmActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmActualizarProductoActionPerformed
        FrmActualizarProducto ventana = new FrmActualizarProducto();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmActualizarProductoActionPerformed

    private void FrmConsultarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmConsultarInventarioActionPerformed
        FrmConsultarInventario ventana = new FrmConsultarInventario();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmConsultarInventarioActionPerformed

    private void FrmActualizarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmActualizarInventarioActionPerformed
        FrmActualizarInventario ventana = new FrmActualizarInventario();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmActualizarInventarioActionPerformed

    private void FrmConsultarActuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmConsultarActuInventarioActionPerformed
        FrmConsultarActuInventario ventana = new FrmConsultarActuInventario();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmConsultarActuInventarioActionPerformed

    private void FrmRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmRegistrarVentaActionPerformed
        FrmRegistrarVenta ventana = new FrmRegistrarVenta();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmRegistrarVentaActionPerformed

    private void FrmConsultarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmConsultarVentaActionPerformed
        FrmConsultarVenta ventana = new FrmConsultarVenta();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmConsultarVentaActionPerformed

    private void FrmImprimirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmImprimirVentaActionPerformed
        FrmImprimirVenta ventana = new FrmImprimirVenta();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmImprimirVentaActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
       
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void FrmEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmEliminarVentaActionPerformed
        FrmEliminarVenta ventana = new FrmEliminarVenta();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_FrmEliminarVentaActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarraMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarraMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarraMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarraMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarraMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ACTUALIZAR;
    private javax.swing.JMenu CONSULTAR;
    private javax.swing.JMenu ELIMINAR;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem FrmActualizarInventario;
    private javax.swing.JMenuItem FrmActualizarProducto;
    private javax.swing.JMenuItem FrmConsultarActuInventario;
    private javax.swing.JMenuItem FrmConsultarInventario;
    private javax.swing.JMenuItem FrmConsultarProducto;
    private javax.swing.JMenuItem FrmConsultarVenta;
    private javax.swing.JMenuItem FrmEliminarProducto;
    private javax.swing.JMenuItem FrmEliminarVenta;
    private javax.swing.JMenuItem FrmImprimirVenta;
    private javax.swing.JMenuItem FrmRegistrarProducto;
    private javax.swing.JMenuItem FrmRegistrarVenta;
    private javax.swing.JMenu REGISTRAR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
