/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Menus;
import Clases.Inventario;
import Clases.Productos;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.HashMap;
import java.util.Scanner;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author rauli
 */
public class FrmActualizarInventario extends javax.swing.JInternalFrame {

    
    HttpClient Cliente = HttpClient.newBuilder().version(HttpClient.Version.HTTP_2).build();
    String Url = "http://localhost/APII/IndexTabla2.php";
    ObjectMapper mapper = new ObjectMapper();
    
    /**
     * Creates new form FrmActualizarInventario
     */
    public FrmActualizarInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JSpinner();
        btnGuardarActu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtId = new javax.swing.JSpinner();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar Inventario");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Id Producto:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Cantidad:");

        txtCantidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnGuardarActu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardarActu.setText("GUARDAR ACTUALIZACION");
        btnGuardarActu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("ID del Producto:");

        txtIdProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnGuardarActu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnGuardarActu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActuActionPerformed
     
        
        HashMap parametros = new HashMap();
        Inventario producto = new Inventario();
       
        producto.setId((Integer) txtId.getValue());
        producto.setCantidad((Integer) txtCantidad.getValue());

        parametros.put("id",producto.getId());
        parametros.put("cantidad",producto.getCantidad());
        
        try{
            
        String DatosProducto = mapper.writeValueAsString(parametros);
        
        HttpRequest request = HttpRequest.newBuilder().PUT(HttpRequest.BodyPublishers.ofString(DatosProducto)).
            uri(URI.create(Url)).build();
        
        HttpResponse<String> response = Cliente.send(request, HttpResponse.BodyHandlers.ofString());
        
        if(response.body() == "200"){
            JOptionPane.showMessageDialog(null,"PRODUCTO ACTUALIZADO");
        }else{ 
            JOptionPane.showMessageDialog(null,"PRODUCTO ACTUALIZADO");
        }
        
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"ERROR: ");
        }
    }//GEN-LAST:event_btnGuardarActuActionPerformed

    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         try{
             
            URL url=new URL("http://localhost/APII/IndexTabla2.php?id="+txtIdProd.getValue()+"");
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.connect();
            int responseCode = conn.getResponseCode();
            
            
            URL url2=new URL("http://localhost/APII/IndexTabla1.php?idprod="+txtIdProd.getValue()+"");
            HttpURLConnection conn2 = (HttpURLConnection) url2.openConnection();
            conn2.setRequestMethod("GET");
            conn2.connect();
            int responseCode2 = conn2.getResponseCode();

            
            if(responseCode == 200 && responseCode2 == 200 ){
                
                StringBuilder informationString = new StringBuilder();
                Scanner scanner = new Scanner(url.openStream());
                
                StringBuilder informationString2 = new StringBuilder();
                Scanner scanner2 = new Scanner(url2.openStream());
                
                while(scanner.hasNext() && scanner2.hasNext()){
                    informationString.append(scanner.nextLine());
                    informationString2.append(scanner2.nextLine());
                }

                scanner.close();
                scanner2.close();
                //System.out.println(informationString);

                JSONArray jsonArray = new JSONArray(informationString.toString());
                JSONObject jsonObject = jsonArray.getJSONObject(0);
                txtId.setValue(jsonObject.getInt("id"));
                txtCantidad.setValue(jsonObject.getInt("cantidad"));
                
                
                JSONArray jsonArray2 = new JSONArray(informationString2.toString());
                JSONObject jsonObject2 = jsonArray2.getJSONObject(0);
                txtNombre.setText(jsonObject2.getString("nombre"));

               
            }else{
                JOptionPane.showMessageDialog(null,"ERROR: ID de Producto no Encontrado, \n porfavor ingrese primero el producto  ");
                //throw new RuntimeException("Ocurrio un Error "+ responseCode);
            }

        } catch(Exception e){
               JOptionPane.showMessageDialog(null,"ERROR: ID de Producto no Encontrado, \n porfavor ingrese primero el producto  ");
                txtId.setValue(0);
                txtCantidad.setValue(0);
                txtNombre.setText("");
                //e.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardarActu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner txtCantidad;
    private javax.swing.JSpinner txtId;
    private javax.swing.JSpinner txtIdProd;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
