/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Menus;
import Clases.ActuInventario;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rauli
 */
public class FrmConsultarActuInventario extends javax.swing.JInternalFrame {

    HttpClient Cliente = HttpClient.newBuilder().version(HttpClient.Version.HTTP_2).build();
    DefaultTableModel modelInventario;
    String Url = "http://localhost/APII/IndexTabla3.php";
    ObjectMapper mapper = new ObjectMapper();
    
    
    /**
     * Creates new form FrmConsultarActuInventario
     */
    public FrmConsultarActuInventario() {
        initComponents();
        modelInventario= (DefaultTableModel)TablaActuInventario.getModel();
        Mostrar();
    }
    
    
    private void Mostrar(){
    
    HttpRequest Peticion = HttpRequest.newBuilder().GET().
            uri(URI.create(Url)).build();
    
     try{
         
        HttpResponse<String> response = Cliente.send(Peticion,HttpResponse.BodyHandlers.ofString());
        List<ActuInventario> productosInventario = getData(response.body(),new TypeReference<List<ActuInventario>>(){
        });
        
         //System.out.println(ProductoLista.size());
         for(ActuInventario inventario:productosInventario){
             Object datos[]={inventario.getNumero_de_factura(),inventario.getFecha_de_compra(),inventario.getCantidad(),inventario.getId()};
             modelInventario.addRow(datos);
         }
         
         
        }catch(Exception e){
         }
   
    }
    
    
     private <T> T getData(String json,TypeReference<T> referencia)
     {
         try {
             return mapper.readValue(json, referencia);
         } catch (Exception e) {e.printStackTrace();
         }
          return null;
     }
     
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaActuInventario = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        TablaActuInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. de Factura", "Fecha de Compra", "Cantidad", "Id Producto"
            }
        ));
        jScrollPane1.setViewportView(TablaActuInventario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaActuInventario;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
