/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Menus;
import br.com.adilson.util.Extenso;

import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Scanner;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

import br.com.adilson.util.PrinterMatrix;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;



public class FrmImprimirVenta extends javax.swing.JInternalFrame {


    
    private void ImprimirTicket(){
    
    PrinterMatrix printer = new PrinterMatrix();
    
    /*
    String Id_venta;
    Id_venta = txtId_Venta.getValue().toString();*/
    
    Integer id_venta         = (Integer) txtId_Venta.getValue();
    Integer id_producto      = (Integer) txtId_Producto.getValue();
    String nombre_producto   = txtNombre_Producto.getText();
    Integer precio           = (Integer) txtPrecio.getValue();
    Integer cantidad         = (Integer) txtCantidad.getValue();
    Integer importe          = (Integer) txtImporte.getValue(); 
    String fecha_venta       = txtFecha_Venta.getText();

    Extenso e = new Extenso();
    
    e.setNumber(101.85);
    
    /*Tamaño de hoja de impresion izq= vertical, der=horizontal*/
    /*Tamaño de columna de la 1 a la 32*/
    /*Tamaño de fila de la 1 a la 9*/
    printer.setOutSize(12, 32);
    
    /*No. Linea(fila), No Columna Inicio, No columna Final, Que se quiere imprimir*/
    printer.printCharAtCol(1, 1, 32, "=");
    
    printer.printTextWrap(1, 2, 8, 32, "FACTURA DE VENTA");
                      /*linI, linE, colI, colE, text*/
    printer.printTextWrap(2, 3, 1, 32, "ID Venta:    "+id_venta);
    printer.printTextWrap(3, 3, 1, 32, "ID Producto: "+id_producto);
    printer.printTextWrap(4, 3, 1, 32, "Nombre Prod: "+nombre_producto);
    printer.printTextWrap(5, 3, 1, 32, "Precio:      "+precio);
    printer.printTextWrap(6, 3, 1, 32, "Cantidad:    "+cantidad);
    printer.printTextWrap(7, 3, 1, 32, "Importe:     "+importe);
    printer.printTextWrap(8, 3, 1, 32, "Fecha Venta: "+fecha_venta);
        
        printer.toFile("Impresion.txt");
        
    FileInputStream inputStream = null;
    
    try{
        inputStream = new FileInputStream("Impresion.txt");
    }catch(FileNotFoundException ex){
        ex.printStackTrace();
    }
        
    if(inputStream == null){
        return;
    }
    
    DocFlavor docFormat = DocFlavor.INPUT_STREAM.AUTOSENSE;
    Doc document = new SimpleDoc(inputStream, docFormat, null);
    
    PrintRequestAttributeSet attributeSet = new HashPrintRequestAttributeSet();
    PrintService defaultPrintService = PrintServiceLookup.lookupDefaultPrintService();
    
    if(defaultPrintService != null)
    {
        DocPrintJob printJob = defaultPrintService.createPrintJob();
        
        try{
            printJob.print(document, attributeSet);
        }catch(Exception ex){
            System.out.println("Error: "+ex.toString());
        }
        
    }else{
        System.err.println("No hay una Impresora Instalada");
    
    }
        
    
    
    
    }
    
    
    
    
    
    /**
     * Creates new form FrmImprimirVenta
     */
    public FrmImprimirVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId_Venta = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId_Producto = new javax.swing.JSpinner();
        txtNombre_Producto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JSpinner();
        txtCantidad = new javax.swing.JSpinner();
        txtImporte = new javax.swing.JSpinner();
        txtFecha_Venta = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Imprimir Venta");

        txtId_Venta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtId_Venta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("ID Venta:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("ID Producto:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Nombre Producto:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Precio por Unidad:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Cantidad: ");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Importe:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Fecha de la Venta:");

        txtId_Producto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtNombre_Producto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_ProductoActionPerformed(evt);
            }
        });

        txtPrecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtCantidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtImporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtFecha_Venta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnImprimir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(txtId_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(txtId_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(txtNombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(txtFecha_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(txtId_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(txtNombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(txtFecha_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombre_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_ProductoActionPerformed

    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         try{
             
            URL url=new URL("http://localhost/APII/IndexTabla4.php?id_venta="+txtId_Venta.getValue()+"");
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.connect();
            
            int responseCode = conn.getResponseCode();
            
            if(responseCode == 200){
                
                StringBuilder informationString = new StringBuilder();
                Scanner scanner = new Scanner(url.openStream());
                
                
                while(scanner.hasNext()){
                    informationString.append(scanner.nextLine());
 
                }

                scanner.close();
                //System.out.println(informationString);

                JSONArray jsonArray = new JSONArray(informationString.toString());
                JSONObject jsonObject = jsonArray.getJSONObject(0);
                
                txtId_Producto.setValue(jsonObject.getInt("id_producto"));
                txtNombre_Producto.setText(jsonObject.getString("nombre_producto"));
                txtPrecio.setValue(jsonObject.getInt("precio"));
                txtCantidad.setValue(jsonObject.getInt("cantidad"));
                txtImporte.setValue(jsonObject.getInt("importe"));
                txtFecha_Venta.setText(jsonObject.getString("fecha_venta"));
 
            }else{
                JOptionPane.showMessageDialog(null,"ERROR: ID de Venta no Encontrado, \n porfavor ingrese la venta primero. ");
                //throw new RuntimeException("Ocurrio un Error "+ responseCode);
            }

        } catch(Exception e){
                JOptionPane.showMessageDialog(null,"ERROR: ID de Venta no Encontrado, \n porfavor ingrese la venta primero. ");
                
                txtId_Producto.setValue(0);
                txtNombre_Producto.setText("");
                txtPrecio.setValue(0);
                txtCantidad.setValue(0);
                txtImporte.setValue(0); 
                txtFecha_Venta.setText("");

                //e.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        ImprimirTicket();
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner txtCantidad;
    private javax.swing.JTextField txtFecha_Venta;
    private javax.swing.JSpinner txtId_Producto;
    private javax.swing.JSpinner txtId_Venta;
    private javax.swing.JSpinner txtImporte;
    private javax.swing.JTextField txtNombre_Producto;
    private javax.swing.JSpinner txtPrecio;
    // End of variables declaration//GEN-END:variables
}
