/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Menus;
import Clases.Ventas;


import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.HashMap;
import java.util.Scanner;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author rauli
 */
public class FrmRegistrarVenta extends javax.swing.JInternalFrame {

    HttpClient Cliente = HttpClient.newBuilder().version(HttpClient.Version.HTTP_2).build();
    String Url = "http://localhost/APII/IndexTabla4.php";
    ObjectMapper mapper = new ObjectMapper();
    
    
    /**
     * Creates new form FrmRegistrarVenta
     */
    public FrmRegistrarVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId_Venta = new javax.swing.JSpinner();
        txtFecha_Venta = new javax.swing.JTextField();
        txtNombre_Producto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JSpinner();
        txtId_Producto = new javax.swing.JSpinner();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JSpinner();
        txtImporte = new javax.swing.JSpinner();
        btnGenerarImporte = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Venta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("ID Venta:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("ID Producto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Fecha de la Venta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Precio por Unidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Nombre Producto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        txtId_Venta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtId_Venta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtId_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 130, 30));

        txtFecha_Venta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtFecha_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 190, 30));

        txtNombre_Producto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_ProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 280, 30));

        txtPrecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 130, 30));

        txtId_Producto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtId_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 130, 31));

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardar.setText("GUARDAR REGISTRO");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 270, 52));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Cantidad: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Importe:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 184, 32));

        txtImporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 184, 32));

        btnGenerarImporte.setText("Generar");
        btnGenerarImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarImporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        HashMap parametros = new HashMap();
        Ventas producto = new Ventas();
       
        producto.setId_venta((Integer) txtId_Venta.getValue());
        producto.setId_producto((Integer) txtId_Producto.getValue());
        producto.setNombre_producto(txtNombre_Producto.getText());
        producto.setPrecio((Integer) txtPrecio.getValue());
        producto.setCantidad((Integer) txtCantidad.getValue());
        producto.setImporte((Integer) txtImporte.getValue());
        producto.setFecha_venta(txtFecha_Venta.getText());
        
        parametros.put("id_venta",producto.getId_venta());
        parametros.put("id_producto",producto.getId_producto());
        parametros.put("nombre_producto",producto.getNombre_producto());
        parametros.put("precio",producto.getPrecio());
        parametros.put("cantidad",producto.getCantidad());
        parametros.put("importe",producto.getImporte());
        parametros.put("fecha_venta",producto.getFecha_venta());
        
        
        
        try{
            
        String DatosProducto = mapper.writeValueAsString(parametros);
        
        HttpRequest request = HttpRequest.newBuilder().POST(HttpRequest.BodyPublishers.ofString(DatosProducto)).
            uri(URI.create(Url)).build();
        
        HttpResponse<String> response = Cliente.send(request, HttpResponse.BodyHandlers.ofString());
        
        if(response.body().trim().equals("200")){
            JOptionPane.showMessageDialog(null,"VENTA REGISTRADA");
        }else{ 
            JOptionPane.showMessageDialog(null,"VENTA REGISTRADA");
            
        }
        
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"ERROR: ");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         try{
             
            URL url=new URL("http://localhost/APII/IndexTabla1.php?idprod="+txtId_Producto.getValue()+"");
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.connect();
            
            int responseCode = conn.getResponseCode();
            
            if(responseCode == 200){
                
                StringBuilder informationString = new StringBuilder();
                Scanner scanner = new Scanner(url.openStream());
                
                
                while(scanner.hasNext()){
                    informationString.append(scanner.nextLine());
 
                }

                scanner.close();
                //System.out.println(informationString);

                JSONArray jsonArray = new JSONArray(informationString.toString());
                JSONObject jsonObject = jsonArray.getJSONObject(0);
                txtPrecio.setValue(jsonObject.getInt("precio"));
                txtNombre_Producto.setText(jsonObject.getString("nombre"));

                

            }else{
                JOptionPane.showMessageDialog(null,"ERROR: ID de Producto no Encontrado, \n porfavor ingrese primero el producto  ");
                //throw new RuntimeException("Ocurrio un Error "+ responseCode);
            }

        } catch(Exception e){
                JOptionPane.showMessageDialog(null,"ERROR: ID de Producto no Encontrado, \n porfavor ingrese primero el producto  ");
                txtPrecio.setValue(0);
                txtNombre_Producto.setText("");

                //e.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarImporteActionPerformed
        Integer Importe;
        Importe = (Integer) txtPrecio.getValue() * (Integer) txtCantidad.getValue() ;
        txtImporte.setValue(Importe);
    }//GEN-LAST:event_btnGenerarImporteActionPerformed

    private void txtNombre_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_ProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerarImporte;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner txtCantidad;
    private javax.swing.JTextField txtFecha_Venta;
    private javax.swing.JSpinner txtId_Producto;
    private javax.swing.JSpinner txtId_Venta;
    private javax.swing.JSpinner txtImporte;
    private javax.swing.JTextField txtNombre_Producto;
    private javax.swing.JSpinner txtPrecio;
    // End of variables declaration//GEN-END:variables
}
